name: Ideia
description: Sugira uma funcionalidade
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Como você imagina?
  - type: dropdown
    id: version
    attributes:
      label: Para qual versão?
      options: [v2, v3, não sei]
