name: Idea
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How do you picture it?
  - type: dropdown
    id: version
    attributes:
      label: Target version
      options: [v2, v3, not sure]
