import '@fontsource/anton/400.css'
import '@fontsource/barlow-semi-condensed/400.css'
import '@fontsource/barlow-semi-condensed/500.css'
import '@fontsource/barlow-semi-condensed/600.css'
import '@fontsource/special-elite/400.css'
import '@fontsource/jetbrains-mono/400.css'
