import { beforeEach, describe, expect, it } from 'vitest'
import {
  applySubagentLine,
  applyTranscriptLine,
  createSession,
  type TrackedSession,
} from '../src/main/model/sessionReducer'
import {
  aiTitle,
  assistantText,
  customTitle,
  CWD,
  resetClock,
  SESSION_ID,
  taskNotification,
  toolResult,
  toolUse,
  userText,
} from './fixtures/lines'

const replay = (lines: unknown[]): TrackedSession =>
  lines.reduce(applyTranscriptLine, createSession(SESSION_ID))

beforeEach(resetClock)

describe('title', () => {
  it('uses the AI-generated title', () => {
    expect(replay([aiTitle('Fix the Batmobile')]).title).toBe('Fix the Batmobile')
  })

  it('prefers a custom title over the AI title, whatever the order', () => {
    expect(replay([customTitle('Gotham patrol'), aiTitle('Fix the Batmobile')]).title).toBe('Gotham patrol')
  })
})

describe('messages', () => {
  it('records user prompts and assistant replies in order', () => {
    const s = replay([userText('Where is the Riddler?'), assistantText('Checking the GCPD files.')])
    expect(s.messages).toEqual([
      { role: 'user', text: 'Where is the Riddler?', at: '2026-01-01T00:00:01.000Z' },
      { role: 'assistant', text: 'Checking the GCPD files.', at: '2026-01-01T00:00:02.000Z' },
    ])
  })

  it('ignores tool calls and tool results', () => {
    const s = replay([toolUse('toolu_1', 'Bash', { command: 'ls' }), toolResult('toolu_1', { stdout: 'x' })])
    expect(s.messages).toEqual([])
  })

  it('ignores lines Claude Code injects on the user side', () => {
    const s = replay([
      { ...userText('Caveat: the messages below were generated by the user'), isMeta: true },
      userText('<command-name>/clear</command-name>'),
      userText('<local-command-stdout>Cleared</local-command-stdout>'),
      userText('<task-notification><task-id>b1</task-id></task-notification>'),
    ])
    expect(s.messages).toEqual([])
  })

  it('ignores injected text in block-shaped user content too', () => {
    const s = replay([
      {
        ...userText(''),
        message: { role: 'user', content: [{ type: 'text', text: '<system-note>auto</system-note>' }] },
      },
    ])
    expect(s.messages).toEqual([])
  })

  it('keeps only the 20 most recent messages', () => {
    const s = replay(Array.from({ length: 25 }, (_, i) => assistantText(`reply ${i}`)))
    expect(s.messages).toHaveLength(20)
    expect(s.messages[0]?.text).toBe('reply 5')
  })

  it('tracks cwd and the time of the latest activity', () => {
    const s = replay([userText('hi'), assistantText('hello')])
    expect(s.cwd).toBe(CWD)
    expect(s.lastActivityAt).toBe('2026-01-01T00:00:02.000Z')
  })
})

describe('tasks', () => {
  const createTask = (toolUseId: string, id: string, subject: string) => [
    toolUse(toolUseId, 'TaskCreate', {
      subject,
      description: `Do: ${subject}`,
      activeForm: `Doing ${subject}`,
    }),
    toolResult(toolUseId, { task: { id, subject } }),
  ]
  const updateTask = (toolUseId: string, input: Record<string, unknown>, result: Record<string, unknown>) => [
    toolUse(toolUseId, 'TaskUpdate', input),
    toolResult(toolUseId, { success: true, ...result }),
  ]

  it('adds a pending task when TaskCreate succeeds', () => {
    const s = replay(createTask('toolu_1', '1', 'Find the Riddler'))
    expect(s.tasks).toEqual([
      {
        id: '1',
        subject: 'Find the Riddler',
        description: 'Do: Find the Riddler',
        activeForm: 'Doing Find the Riddler',
        status: 'pending',
        history: [{ status: 'pending', at: '2026-01-01T00:00:02.000Z' }],
      },
    ])
  })

  it('does not add a task when TaskCreate fails', () => {
    const s = replay([
      toolUse('toolu_1', 'TaskCreate', { subject: 'x' }),
      toolResult('toolu_1', 'Error: invalid', true),
    ])
    expect(s.tasks).toEqual([])
  })

  it('moves a task through its statuses and keeps the history', () => {
    const s = replay([
      ...createTask('toolu_1', '1', 'Find the Riddler'),
      ...updateTask(
        'toolu_2',
        { taskId: '1', status: 'in_progress' },
        { taskId: '1', updatedFields: ['status'], statusChange: { from: 'pending', to: 'in_progress' } },
      ),
      ...updateTask(
        'toolu_3',
        { taskId: '1', status: 'completed' },
        { taskId: '1', updatedFields: ['status'], statusChange: { from: 'in_progress', to: 'completed' } },
      ),
    ])
    expect(s.tasks[0]?.status).toBe('completed')
    expect(s.tasks[0]?.history).toEqual([
      { status: 'pending', at: '2026-01-01T00:00:02.000Z' },
      { status: 'in_progress', at: '2026-01-01T00:00:04.000Z' },
      { status: 'completed', at: '2026-01-01T00:00:06.000Z' },
    ])
  })

  it('applies subject and description edits', () => {
    const s = replay([
      ...createTask('toolu_1', '1', 'Find the Riddler'),
      ...updateTask(
        'toolu_2',
        { taskId: '1', subject: 'Catch the Riddler', description: 'Before the flood' },
        { taskId: '1', updatedFields: ['subject', 'description'] },
      ),
    ])
    expect(s.tasks[0]).toMatchObject({ subject: 'Catch the Riddler', description: 'Before the flood' })
  })

  it('drops deleted tasks', () => {
    const s = replay([
      ...createTask('toolu_1', '1', 'Find the Riddler'),
      ...createTask('toolu_2', '2', 'Call Alfred'),
      ...updateTask(
        'toolu_3',
        { taskId: '1', status: 'deleted' },
        { taskId: '1', updatedFields: ['status'], statusChange: { from: 'pending', to: 'deleted' } },
      ),
    ])
    expect(s.tasks.map((t) => t.id)).toEqual(['2'])
  })
})

describe('subagents', () => {
  const spawn = (toolUseId: string) =>
    toolUse(toolUseId, 'Agent', {
      description: 'Search the archives',
      subagent_type: 'Explore',
      prompt: 'Find every record of the Riddler',
    })

  it('shows a subagent as running as soon as it is spawned', () => {
    expect(replay([spawn('toolu_a')]).subagents).toEqual([
      {
        toolUseId: 'toolu_a',
        description: 'Search the archives',
        agentType: 'Explore',
        prompt: 'Find every record of the Riddler',
        status: 'running',
        startedAt: '2026-01-01T00:00:01.000Z',
      },
    ])
  })

  it('completes a foreground subagent when its result arrives', () => {
    const s = replay([spawn('toolu_a'), toolResult('toolu_a', { status: 'completed', content: [] })])
    expect(s.subagents[0]).toMatchObject({ status: 'completed', endedAt: '2026-01-01T00:00:02.000Z' })
  })

  it('marks a subagent as failed when its tool call errors', () => {
    const s = replay([spawn('toolu_a'), toolResult('toolu_a', 'Error', true)])
    expect(s.subagents[0]?.status).toBe('failed')
  })

  const launched = () => toolResult('toolu_a', { isAsync: true, status: 'async_launched', agentId: 'a1b2' })

  it('keeps a background subagent running after it is launched', () => {
    const s = replay([spawn('toolu_a'), launched()])
    expect(s.subagents[0]).toMatchObject({ status: 'running', agentId: 'a1b2' })
  })

  it('completes a background subagent from its task notification', () => {
    const done = replay([
      spawn('toolu_a'),
      launched(),
      taskNotification({
        taskId: 'a1b2',
        toolUseId: 'toolu_a',
        status: 'completed',
        summary: 'Found 3 files',
      }),
    ])
    expect(done.subagents[0]).toMatchObject({
      status: 'completed',
      summary: 'Found 3 files',
      endedAt: '2026-01-01T00:00:03.000Z',
    })
  })
})

describe('background commands', () => {
  const runInBackground = (toolUseId: string, jobId: string) => [
    toolUse(toolUseId, 'Bash', {
      command: 'npm run dev',
      description: 'Start dev server',
      run_in_background: true,
    }),
    toolResult(toolUseId, { stdout: '', stderr: '', interrupted: false, backgroundTaskId: jobId }),
  ]

  it('tracks a command that went to the background', () => {
    expect(replay(runInBackground('toolu_b', 'bjob1')).background).toEqual([
      {
        id: 'bjob1',
        toolUseId: 'toolu_b',
        command: 'npm run dev',
        description: 'Start dev server',
        status: 'running',
        startedAt: '2026-01-01T00:00:02.000Z',
      },
    ])
  })

  it('does not track foreground commands', () => {
    const s = replay([toolUse('toolu_b', 'Bash', { command: 'ls' }), toolResult('toolu_b', { stdout: 'a' })])
    expect(s.background).toEqual([])
  })

  it('finishes a background command from its task notification', () => {
    const s = replay([
      ...runInBackground('toolu_b', 'bjob1'),
      taskNotification({ taskId: 'bjob1', toolUseId: 'toolu_b', status: 'failed' }),
    ])
    expect(s.background[0]).toMatchObject({ status: 'failed', endedAt: '2026-01-01T00:00:03.000Z' })
  })

  it('marks a background command as stopped by TaskStop', () => {
    const s = replay([
      ...runInBackground('toolu_b', 'bjob1'),
      toolUse('toolu_s', 'TaskStop', { task_id: 'bjob1' }),
      toolResult('toolu_s', {
        message: 'Successfully stopped task',
        task_id: 'bjob1',
        task_type: 'local_bash',
      }),
    ])
    expect(s.background[0]).toMatchObject({ status: 'stopped', endedAt: '2026-01-01T00:00:04.000Z' })
  })

  it('ignores the duplicate "remove" queue operation', () => {
    const s = replay([
      ...runInBackground('toolu_b', 'bjob1'),
      taskNotification({ taskId: 'bjob1', toolUseId: 'toolu_b', status: 'completed', operation: 'remove' }),
    ])
    expect(s.background[0]?.status).toBe('running')
  })
})

describe('replayed or duplicated lines', () => {
  it('does not list a subagent twice when its spawn line is replayed', () => {
    const spawn = toolUse('toolu_a', 'Agent', { description: 'Search', subagent_type: 'Explore' })
    expect(replay([spawn, spawn]).subagents).toHaveLength(1)
  })

  it('finishes a run from a task notification delivered as a user line', () => {
    const s = replay([
      toolUse('toolu_b', 'Bash', { command: 'npm run dev', run_in_background: true }),
      toolResult('toolu_b', { backgroundTaskId: 'bjob1' }),
      userText(
        '<task-notification>\n<task-id>bjob1</task-id>\n<tool-use-id>toolu_b</tool-use-id>\n<status>completed</status>\n</task-notification>',
      ),
    ])
    expect(s.background[0]).toMatchObject({ status: 'completed', endedAt: '2026-01-01T00:00:03.000Z' })
  })
})

describe('subagent transcripts', () => {
  const spawned = () => [
    toolUse('toolu_a', 'Agent', { description: 'Search', subagent_type: 'Explore' }),
    toolResult('toolu_a', { isAsync: true, status: 'async_launched', agentId: 'a1b2' }),
  ]

  it("shows a subagent's latest reply, linked through its meta.json tool_use id", () => {
    const s = applySubagentLine(
      replay(spawned()),
      { agentId: 'zzz', toolUseId: 'toolu_a' },
      assistantText('Found 3 files'),
    )
    expect(s.subagents[0]?.lastMessage).toBe('Found 3 files')
  })

  it('links a subagent transcript through its agent id when meta.json has no tool_use id', () => {
    const s = applySubagentLine(replay(spawned()), { agentId: 'a1b2' }, assistantText('Still looking'))
    expect(s.subagents[0]?.lastMessage).toBe('Still looking')
  })

  it('ignores lines from an agent the session does not know', () => {
    const before = replay(spawned())
    expect(applySubagentLine(before, { agentId: 'other' }, assistantText('hi'))).toBe(before)
  })
})

describe('unexpected task statuses', () => {
  it('ignores a status change to a value Batcave does not know', () => {
    const s = replay([
      toolUse('toolu_1', 'TaskCreate', { subject: 'Find the Riddler' }),
      toolResult('toolu_1', { task: { id: '1', subject: 'Find the Riddler' } }),
      toolUse('toolu_2', 'TaskUpdate', { taskId: '1', status: 'archived' }),
      toolResult('toolu_2', {
        success: true,
        taskId: '1',
        statusChange: { from: 'pending', to: 'archived' },
      }),
    ])
    expect(s.tasks[0]?.status).toBe('pending')
    expect(s.tasks[0]?.history).toHaveLength(1)
  })
})
