/** Channel names shared by the main process and the preload bridge. */
export const IPC = {
  snapshot: 'bat-signal:snapshot',
  getSnapshot: 'bat-signal:get-snapshot',
  markSeen: 'bat-signal:mark-seen',
  getSettings: 'bat-signal:get-settings',
  setSettings: 'bat-signal:set-settings',
  settings: 'bat-signal:settings',
  getMode: 'bat-signal:get-mode',
  setMode: 'bat-signal:set-mode',
  mode: 'bat-signal:mode',
  focusCase: 'bat-signal:focus-case',
  noticeOut: 'bat-signal:notice-out',
  moveSignal: 'bat-signal:move-signal',
  interactive: 'bat-signal:interactive',
  goToTerminal: 'bat-signal:go-to-terminal',
  warmTerminal: 'bat-signal:warm-terminal',
  reopen: 'bat-signal:reopen',
  watchHeight: 'bat-signal:watch-height',
  hide: 'bat-signal:hide',
  openSettings: 'bat-signal:open-settings',
  getStatus: 'bat-signal:get-status',
  status: 'bat-signal:status',
  recordShortcut: 'bat-signal:record-shortcut',
  setStartWithWindows: 'bat-signal:set-start-with-windows',
  /** Read again what may have changed outside the app (Task Manager's startup switch). */
  refreshStatus: 'bat-signal:refresh-status',
} as const
